Solution.Web2/Controllers/ActiviteController.cs
using Kaliko.ImageLibrary;
using Kaliko.ImageLibrary.Scaling;
using Solution.Domain.Entities;
using Solution.Service;
using Solution.Web2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using Gnostice.StarDocsSDK;
using Microsoft.AspNet.Identity;

namespace Solution.Web2.Controllers
{
    public class ActiviteController : Controller
    {
        public IUserService MyUser;
        //public ActiviteService MyActiviteService;
        IActiviteService activiteService = new ActiviteService();
        // GET: Activite
        public ActionResult Index(string searchString, int? i)
        {
            var Activites = new List<ActiviteVM>();
            foreach (Activite p in activiteService.SearchClassByName(searchString))
            {
                //if (p.Description.Length > 37)
                //    p.Description = p.Description.Substring(0, 34) + "...";
                Activites.Add(new ActiviteVM()
                {
                    ActiviteID = p.ActiviteID,
                    Title = p.Title,
                    Description = p.Description,
                    Affiche = p.Affiche,
                    Document = p.Document,
                    Theme = p.Theme,
                    Outils = p.Outils,
                    AgeMin = p.AgeMin,
                    AgeMax = p.AgeMax,
                    ClassSize= p.ClassSize,
                    Duration=p.Duration,
                    Professor=p.Professor,
                    Start= p.Start,
                    Location = p.Location,
                    //    nomuser = User.Identity.GetUserName(),
                    UserId = User.Identity.GetUserId<int>()
            });

            }
            return View(Activites.ToPagedList(i ?? 1 ,3));

        }

        // GET: Activite/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activite A;
            A = activiteService.GetById((int)id);
            if (A == null) { return HttpNotFound(); }
            ActiviteVM pvm = new ActiviteVM()
            {
                ActiviteID = A.ActiviteID,
                Title = A.Title,
                Description = A.Description,
                Affiche = A.Affiche,
                Document = A.Document,
                Theme = A.Theme,
                Outils = A.Outils,
                AgeMin = A.AgeMin,
                AgeMax = A.AgeMax,
                ClassSize = A.ClassSize,
                Duration = A.Duration,
                Professor = A.Professor,
                Start = A.Start,
                Location = A.Location,
                //    nomuser = User.Identity.GetUserName(),
                UserId = User.Identity.GetUserId<int>()
        };
            var t = activiteService.GetMany();
            foreach (Activite Act in t)
            {
                var path1 = Path.Combine(Server.MapPath("~/Content/Uploads"), Act.Affiche);
                KalikoImage image = new KalikoImage(path1);
                KalikoImage thumb = image.Scale(new CropScaling(90, 80));
                var path2 = Path.Combine(Server.MapPath("~/Content/Uploads"), Act.Title + "latest.jpg");
                thumb.SaveJpg(path2, 99);
            }
            List<Activite> Courses = t.ToList();
            ViewData["Courses"] = Courses;
            return View(pvm);
        }

        // GET: Activite/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Activite/Create

        [HttpPost]
        public ActionResult Create(ActiviteVM ActiviteVM, HttpPostedFileBase Affiche)
        {
            //if (!ModelState.IsValid || Affiche == null || Affiche.ContentLength == 0|| ActiviteVM.AgeMin>ActiviteVM.AgeMax)
            //{
            //    //ModelState.AddModelError("", "Verify your form !");
            //    RedirectToAction("Create");
            //}
            if (ActiviteVM.AgeMin > ActiviteVM.AgeMax)
            {
                ModelState.AddModelError("AgeMin", "Age Minimum est erronée");
                ModelState.AddModelError("AgeMax", "Age Maximum est erronée");
                return View(ActiviteVM);
            }
            try
            {
                Activite ActiviteDomain = new Activite()
            {

                Title = ActiviteVM.Title,
                Description = ActiviteVM.Description,
                Affiche = Affiche.FileName,
                Theme = ActiviteVM.Theme,
                Type = ActiviteVM.Type,
                Outils = ActiviteVM.Outils,
                AgeMin = ActiviteVM.AgeMin,
                AgeMax = ActiviteVM.AgeMax,
                ClassSize = ActiviteVM.ClassSize,
                Duration = ActiviteVM.Duration,
                Professor = ActiviteVM.Professor,
                Start = ActiviteVM.Start,
                Location = ActiviteVM.Location,
                Document= "",
                //    nomuser = User.Identity.GetUserName(),
                UserId = User.Identity.GetUserId<int>()
            };

            activiteService.Add(ActiviteDomain);
            activiteService.Commit();

            var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Affiche.FileName);
            Affiche.SaveAs(path);
            return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(ActiviteVM);
            }

        }


        // GET: Activite/Edit/5
        public ActionResult Edit(int id)
        {

            Activite p = activiteService.GetById((int)id);
            ActiviteVM pm = new ActiviteVM()
            {
                ActiviteID = p.ActiviteID,
                Title = p.Title,
                Description = p.Description,
                Affiche = p.Affiche,
                Theme = p.Theme,
                Outils = p.Outils,
                AgeMin = p.AgeMin,
                AgeMax = p.AgeMax,
                ClassSize = p.ClassSize,
                Duration = p.Duration,
                Professor = p.Professor,
                Start = p.Start,
                Location = p.Location,
                //    nomuser = User.Identity.GetUserName(),
                UserId = User.Identity.GetUserId<int>()
        };
            return View(pm);
        }

        // POST: Activite/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ActiviteVM p, HttpPostedFileBase Affiche)
        {
          
                Activite pm = activiteService.GetById((int)id);

                pm.Title = p.Title;
                pm.Description = p.Description;
                pm.Affiche = Affiche.FileName;
                pm.Theme = p.Theme;
                pm.Outils = p.Outils;
                pm.AgeMin = p.AgeMin;
                pm.AgeMax = p.AgeMax;
                pm.ClassSize = p.ClassSize;
                pm.Duration = p.Duration;
                pm.Professor = p.Professor;
                pm.Start = p.Start;
                pm.Location = p.Location;
                    //    nomuser = User.Identity.GetUserName(),
                pm.UserId = User.Identity.GetUserId<int>();

            activiteService.Update(pm);
                activiteService.Commit();

                var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Affiche.FileName);
                Affiche.SaveAs(path);
                return RedirectToAction("Index");
          
        }

        // GET: Activite/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Activite/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Activite p = activiteService.GetById(id);
            activiteService.Delete(p);
            activiteService.Commit();
            // TODO: Add delete logic here

            return RedirectToAction("Index");
        }
        public ActionResult AjoutDocument(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult AjoutDocument(int id, HttpPostedFileBase Doc)
        {
            if ( Doc == null || Doc.ContentLength == 0)
            {
                RedirectToAction("Details", new { id = id });
            }
            try
            {
                Activite pm = activiteService.GetById((int)id);
                pm.Document = Doc.FileName;
                activiteService.Update(pm);
                activiteService.Commit();

                var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Doc.FileName);
                Doc.SaveAs(path);
                return RedirectToAction("Details", new { id = id });

            }
            catch (Exception ex)
            {
                return RedirectToAction("Details", new { id = id });
            }
        }

        public ActionResult SuppDocument(int id)
        {
            try
            {
                Activite pm = activiteService.GetById((int)id);
                pm.Document = null;
                activiteService.Update(pm);
                activiteService.Commit();
                return RedirectToAction("Details", new { id = id });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Details", new { id = id });
            }
        }

        public ActionResult PdfViewer(string Doc)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Doc);
            ViewerSettings viewerSettings = new ViewerSettings();
            viewerSettings.VisibleFileOperationControls.Open = true;
            ViewResponse viewResponse = MvcApplication.StarDocs.Viewer.CreateView(
                new FileObject(path), null, viewerSettings);

Solution.Web2/Views/Activite/AjoutDocument.cshtml
@{
    ViewBag.Title = "AjoutDocument";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>AjoutDocument</h2>
@using (Html.BeginForm("AjoutDocument", "Activite", FormMethod.Post, new {  enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="form-input-styled">
            @Html.TextBox("Doc", null, new
       {
           type = "file",
           @class = "form-input-styled"
       })
            <span class="form-text text-muted">Accepted formats: PDF</span>
        </div>
    </div>
    <input type="submit" value="Save" class="btn btn-default" />

}

Solution.Web2/Views/Activite/Create.cshtml
@model Solution.Web2.Models.ActiviteVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Activite", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ActiviteVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Outils, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Outils, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Outils, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgeMin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgeMin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgeMin, "", new { @class = "text-danger" })
            
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgeMax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgeMax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgeMax, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Start, "{0:yyyy-MM-ddThh:mm:ss}", new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClassSize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassSize, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Professor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Professor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Professor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Affiche, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Affiche", null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Affiche, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
}

Solution.Web2/Views/Activite/Delete.cshtml
@model Solution.Web2.Models.ActiviteVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ActiviteVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Outils)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Outils)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgeMin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgeMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgeMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgeMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Affiche)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Affiche)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Solution.Web2/Views/Activite/Edit.cshtml
@model Solution.Web2.Models.ActiviteVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Activite", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ActiviteVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ActiviteID)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Outils, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Outils, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Outils, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgeMin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgeMin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgeMin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgeMax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgeMax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgeMax, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="form-input-styled">
            @Html.TextBox("Affiche", null, new
       {
           type = "file",
           @class = "form-input-styled"
       })
            @Html.ValidationMessageFor(model => model.Affiche, "", new { @class = "text-danger" })
            <span class="form-text text-muted">Accepted formats: gif, png, jpg. Max file size 2Mb</span>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts{}

Solution.Web2/Views/Activite/Index.cshtml
@model IPagedList<Solution.Web2.Models.ActiviteVM>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<div class="content-wrapper">
    <button type="button" class="btn btn-default"><a href="@Url.Action("Create", "Activite")">Add Activite</a></button>

    <main class="main-content">

        <div class="col-lg-4">
            <div class="sidebar">
                <div class="sidebar-item">
                    <form>
                        @using (Html.BeginForm())
                        {
                            //@Html.TextBox("searchString", "", new { @class = "sidebar sidebar-item form" })
                            <input type="text" name="searchString" placeholder="Search Your Course...">
                            <button type="submit" id="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                        }
                    </form>
                </div>
            </div>
        </div>

        <section class="classes padding-120">
            <div class="container">
                <div class="row">
                    @if (Model != null)
                    {

                        foreach (var item in Model)
                        {

                            @Html.Partial("_DisplayActivite", item)
                        }
                    }
                </div>
            </div>
        </section>
    </main>
</div>
@Html.PagedListPager(Model, i=> Url.Action("Index","Activite",new{ i, search=Request.QueryString["searchString"]}))

@section scripts{}

Solution.Web2/Views/Activite/_DisplayActivite.cshtml
@model Solution.Web2.Models.ActiviteVM
@{string path = "~/Content/Uploads/" + @Model.Affiche;}



<div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="class-item">
        <div class="image">
            <img src="@Url.Content(path)" alt="Affiche" class="img-responsive" />
        </div>
        <ul class="schedule">
            <li>
                <span>Class Size</span>
                <span>@Model.ClassSize</span>
            </li>
            <li>
                <span>Years Old</span>
                <span>@Model.AgeMin - @Model.AgeMax</span>
            </li>
            <li>
                <span>Theme</span>
                <span>@Model.Theme</span>
            </li>
        </ul>
        <div class="content">
            <h4> @Html.ActionLink(@Model.Title, "Details", new { id = Model.ActiviteID })</h4>
            <p><span>Class Time</span> : 08:00 am - 10:00 am</p>
            <p><span>Theme </span>@Model.Theme</p>
            <p>@Model.Description</p>
            <p><span>Outils </span> : @Model.Outils</p>
        </div>
        <div class="address">
            <p><span><i class="fa fa-home" aria-hidden="true"></i></span> @Model.Location</p>
        </div>
    </div><!-- class item -->
</div>




@*<div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="event-item " style="flex:1; padding: 16px;">
        <div class="event-image">
            <img src="@Url.Content(path)" alt="Affiche" class="img-responsive" />
            <div class="date">
                <span>24</span>
                <p>March</p>
            </div>
        </div>
        <div class="event-content" style="width:348px ; max-height:200px">
            <h4>@Model.Title</h4>
            <ul>
                <li><span><i class="fa fa-clock-o" aria-hidden="true"></i></span>08:00 am - 10:00 am</li>
                <li><span><i class="fa fa-home" aria-hidden="true"></i></span>218 New Elephant Road Dhaka</li>
            </ul>
            <p style="width:250px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">@Model.Description</p>
            @Html.ActionLink("Join Now", "Details", new { id = Model.ActiviteID })
        </div>
    </div>*@



    <!-- event blog -->
    <!-- event End here -->
    @section scripts{}