Solution.Web2/Controllers/FormationController.cs
using Microsoft.AspNet.Identity;
using Solution.Domain.Entities;
using Solution.Web2.Models;
using Solution.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kaliko.ImageLibrary;
using Kaliko.ImageLibrary.Scaling;
using PagedList;

namespace Solution.Web2.Controllers
{
    public class FormationController : Controller
    {
        public IUserService MyUser;
        public FormationService MyFormationService;
        public  ParticipationService MyParticipationService;
        public EnfantService MyEnfantService;
        public ActiviteService MyActiviteService;


        public FormationController()
        {
            MyUser = new UserService();
            MyFormationService = new FormationService();
            MyEnfantService = new EnfantService();
            MyParticipationService = new ParticipationService();
            MyActiviteService = new ActiviteService();
        }
        // GET: Formation
        public ActionResult Index(string searchString, int? i)
        {
            var Formations = new List<FormationVM>();
            foreach (Formation p in MyFormationService.SearchFormByName(searchString))
            {

                if (string.IsNullOrEmpty(p.Affiche))
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Front/images/event/event_02.jpg"));
                    KalikoImage image = new KalikoImage(path);
                    KalikoImage thumb = image.Scale(new CropScaling(250, 250));
                    var path2 = Path.Combine(Server.MapPath("~/Content/Uploads"), p.Title + "thumb.jpg");
                    thumb.SaveJpg(path2, 99);
                }
                else
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Uploads"), p.Affiche);
                    KalikoImage image = new KalikoImage(path);
                    KalikoImage thumb = image.Scale(new CropScaling(250, 250));
                    var path2 = Path.Combine(Server.MapPath("~/Content/Uploads"), p.Title + "thumb.jpg");
                    thumb.SaveJpg(path2, 99);
                }
                

                Formations.Add(new FormationVM()
                {
                    FormationID = p.FormationID,
                    Title = p.Title,
                    Start = p.Start,
                    End = p.End,
                    Description = p.Description,
                    // Affiche = p.Affiche,
                    Affiche = p.Title + "thumb.jpg",
                    NbrMax = p.NbrMax,
                    Theme = p.Theme,
                    Location = p.Location,
                    Price = p.Price
                }) ;

            }
            return View(Formations.ToPagedList(i ?? 1, 3));

        }




        //calendar
        public ActionResult Calendar()
        {
            return View();
        }
        public JsonResult GetFormations()
        {
            var Formationss = new List<FormationVM>();
            foreach (Formation p in MyFormationService.GetMany())
            {
                Formationss.Add(new FormationVM()
                {
                    FormationID = p.FormationID,
                    Title = p.Title,
                    Start = p.Start,
                    End = p.End,
                    Description = p.Description,
                    Affiche = p.Affiche,
                    //Affiche = p.Title + "thumb.jpg",
                    NbrMax = p.NbrMax,
                    Theme = p.Theme,
                    Location = p.Location,
                    Price = p.Price,
                    Reserved = p.Reserved,
                    UserId=p.UserId
                }) ;

            }
            return new JsonResult { Data = Formationss, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }





        // GET: Formation/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formation p;
            p = MyFormationService.GetById((int)id);
            if (p == null) { return HttpNotFound(); }
            FormationVM pvm = new FormationVM()
            {
                FormationID= p.FormationID,
                Title = p.Title,
                Affiche = p.Affiche,
                Start = p.Start,
                End = p.End,
                Description = p.Description,
                Location = p.Location,
                Price = p.Price,
                Theme = p.Theme,
                NbrMax = p.NbrMax

            };
             var t = MyActiviteService.GetMany();
            foreach(Activite A in t)
            {
                if (string.IsNullOrEmpty(A.Affiche))
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Front/images/event/event_02.jpg"));
                    KalikoImage image = new KalikoImage(path);
                    KalikoImage thumb = image.Scale(new CropScaling(90, 80));
                    var path2 = Path.Combine(Server.MapPath("~/Content/Uploads"), A.Title + "latest.jpg");
                    thumb.SaveJpg(path2, 99);
                    A.Affiche = A.Title + "latest.jpg";
                }
                else
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Uploads"), A.Affiche);
                    KalikoImage image = new KalikoImage(path);
                    KalikoImage thumb = image.Scale(new CropScaling(90, 80));
                    var path2 = Path.Combine(Server.MapPath("~/Content/Uploads"), A.Title + "latest.jpg");
                    thumb.SaveJpg(path2, 99);
                    A.Affiche = A.Title + "latest.jpg";
                }

            }
            List<Activite> Courses = t.OrderByDescending(act => act.Start).Take(5).ToList();
            ViewData["Courses"] = Courses;

            return View(pvm);
        }

        //get
        public ActionResult Paricipate(int IdFormation)
        {
            var Enfats = new List<EnfantVM>();
            Formation f = MyFormationService.GetById((int)IdFormation);
            IEnumerable<Enfant> pm = MyEnfantService.SearchEnfantByParent(User.Identity.GetUserId<int>());
            foreach (Enfant E in pm)
            {
                if ((f.NbrMax > f.Reserved)&& (!MyParticipationService.dejaInscrit(E.EnfantId,f.FormationID))) { 
                    Enfats.Add(new EnfantVM()
                  {
                     EnfantId= E.EnfantId,
                     Age = E.Age,
                     Image= E.Image,
                     Nom=E.Nom,
                     Prenom = E.Prenom,
                     Sexe=E.Sexe,
                     IdFormation= IdFormation
                    }
                    );
            
                }
            }
            return View(Enfats);
        }

        public ActionResult Paricipate1(int IdEnfant, int IdFormation)
        {

            Formation f = MyFormationService.GetById((int)IdFormation);
            f.Reserved ++;
            Participation p = new Participation()
            {
                EnfantId = IdEnfant,
                FormationID= IdFormation,
                Title= f.Title

            };
            MyFormationService.Update(f);
            MyFormationService.Commit();
            MyParticipationService.Add(p);
            MyParticipationService.Commit();

            return RedirectToAction("Paricipate", new { IdFormation = IdFormation });

        }

        // GET: Formation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Formation/Create
        [HttpPost]
        public ActionResult Create(FormationVM FormationVM, HttpPostedFileBase Affiche)
        {
            //if (!ModelState.IsValid || Affiche == null || Affiche.ContentLength == 0)
            //{
            //    RedirectToAction("Create");
            //}
            if (FormationVM.Start > FormationVM.End)
            {
                ModelState.AddModelError("Start", "Date de début est erronée");
                ModelState.AddModelError("End", "Date de Fin est erronée");
                return View(FormationVM);
            }
                
                    Formation FormationDomain = new Formation()
                    {
                        Title = FormationVM.Title,
                        Start = FormationVM.Start,
                        End = FormationVM.End,
                        Description = FormationVM.Description,
                        Affiche = Affiche.FileName,
                        NbrMax = FormationVM.NbrMax,
                        Theme = FormationVM.Theme,
                        Location = FormationVM.Location,
                        Price = FormationVM.Price,

                        //    nomuser = User.Identity.GetUserName(),
                        UserId = User.Identity.GetUserId<int>()
        };

                    MyFormationService.Add(FormationDomain);
                    MyFormationService.Commit();
                
                    var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Affiche.FileName);
                    Affiche.SaveAs(path);
                    return RedirectToAction("Index");
                

        }

        // GET: Formation/Edit/5
        public ActionResult Edit(int id)
        {

            Formation p = MyFormationService.GetById((int)id);
            FormationVM pm = new FormationVM()
            {
                
                Start = p.Start,
                End = p.End,
                Description = p.Description,
                Affiche = p.Affiche,
                UserId = p.UserId,
                FormationID = p.FormationID,
                Theme = p.Theme,
                Title = p.Title,
                Location = p.Location,
                NbrMax = p.NbrMax,

Solution.Web2/Views/Formation/Create.cshtml
@model Solution.Web2.Models.FormationVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Formation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="review-form">
    <h4>Formation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Start, "{0:yyyy-MM-ddThh:mm:ss}", new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.End, "{0:yyyy-MM-ddThh:mm:ss}", new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.IsFullDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFullDay)
                    @Html.ValidationMessageFor(model => model.IsFullDay, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.NbrMax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NbrMax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NbrMax, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        @Html.LabelFor(model => model.Affiche, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Affiche", null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Affiche, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section scripts {}

Solution.Web2/Views/Formation/Details.cshtml
@model Solution.Web2.Models.FormationVM
@{string path = "~/Content/Uploads/" + @Model.Affiche;}
@using Solution.Domain.Entities;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MyLayout.cshtml";
    IEnumerable<Activite> courses = ViewData["Courses"] as IEnumerable<Activite>;

}

<!-- Page Header Start here -->
<section class="page-header section-notch">
    <div class="overlay">
        <div class="container">
            <h3>Event Details Page</h3>
            <ul>
                <li><a href="@Url.Action("Index", "Formation")">Home</a></li>
                <li>-</li>
                <li>Event Details</li>
            </ul>
        </div><!-- container -->
    </div><!-- overlay -->
</section><!-- page header -->
<!-- Page Header End here -->
<!-- Blog Post Start here -->
<section class="singel-class event-single padding-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="single-post">
                    <div class="post-image">

                        @if (Model.Affiche is null)
                        {
                            <img src="@Url.Content("~/Content/Front/images/event/event_03.jpg")" alt="post image" class="img-responsive">
                        }
                        else
                        {
                            <img src="@Url.Content(path)" alt="post image" class="img-responsive">
                        }
                        <div class="event-counter">
                            <div class="row">
                                <div class="col-md-6 col-xs-12">
                                    <h4>@Model.Title</h4>
                                </div>
                                <div class="col-md-6 col-xs-12">
                                    <ul id="countdown" class="countdown">
                                        <li class="clock-item"><span class="count-number days">00</span><p class="days_text count-text">Days</p></li>

                                        <li class="clock-item"><span class="count-number hours">00</span><p class="hours_text count-text">Hours</p></li>

                                        <li class="clock-item"><span class="count-number minutes">00</span><p class="minutes_text count-text">Min</p></li>

                                        <li class="clock-item"><span class="count-number seconds">00</span><p class="seconds_text count-text">Sec</p></li>
                                    </ul>
                                </div>
                            </div><!-- row -->
                        </div>
                    </div>
                    <div class="post-content">
                        <h3>@Model.Title</h3>
                        <ul class="post-meta">
                            <li><span class="icon flaticon-signs"></span> <a href="#">@Model.Location</a></li>
                            <li><span class="icon flaticon-alarm-clock"></span> <a href="#">Time: @Model.Start</a></li>
                        </ul>
                        <p>@Model.Description</p>
                        <h4>Event Organizer</h4>
                        <p>@Model.Theme</p>

                        @if (Model.Start > DateTime.Now)
                        {
                            @Html.ActionLink("Join Now", "Paricipate", new { IdFormation = Model.FormationID }, new { @class = "button-default" })
                        }
                        else
                        {
                            <a href="#" class="button-default">Expired</a>
                        }

                    </div>
                    <div class="event-map" id="map-canvas"></div>
                </div><!-- single post -->
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="sidebar-item">
                        <form>
                            <input type="text" name="text" placeholder="Search Your Course...">
                            <button><i class="fa fa-search" aria-hidden="true"></i></button>
                        </form>
                    </div><!-- sidebar item -->
            
                    <div class="sidebar-item">
                        <h3 class="sidebar-title">Latest Courses</h3>
                        @foreach (var item in courses)
                        {
                            <ul class="sidebar-posts">
                                <li>
                                    <div class="image">
                                        <a href="@Url.Action("Details", "Activite", new { id = item.ActiviteID })"><img src="@Url.Content("~/Content/Uploads/" + @item.Affiche)" alt="post image" class="img-responsive"></a>
                                    </div>
                                    <div class="content">
                                        <a href="@Url.Action("Details", "Activite", new { id = item.ActiviteID })">@item.Title</a>
                                        <span>@item.Theme</span>
                                    </div>
                                    <br />
                                </li>
          
                            </ul><!-- sidebar-posts -->
                        }
                    </div><!-- sidebar item -->
                    <div class="sidebar-item">
                        <h3 class="sidebar-title">Photos Gallery</h3>

                        <ul class="sidebar-gallery">
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_01.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_02.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_03.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_04.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_05.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_06.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_07.jpg" alt="gallery image" class="img-responsive"></a></li>
                            <li><a href="#"><img src="~/Content/Front/images/blog/gallery_08.jpg" alt="gallery image" class="img-responsive"></a></li>
                        </ul><!-- sidebar-gallery -->
                    </div><!-- sidebar item -->
                </div>
            </div>
        </div>
    </div>
</section>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FormationID }) |
    @Html.ActionLink("Join !", "Paricipate", new { IdFormation = Model.FormationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<!--coundown-->
@section scripts{
    <script type="text/javascript">

        var nextyear = @Model.Start.Month + '/' +  @Model.Start.Day + '/' +  @Model.Start.Year + '  @Model.Start.TimeOfDay';
        //countdwon
        $('#countdown').countdown({
            date: nextyear,
            offset: +2,
            day: 'Day',
            days: 'Days'
        });
    </script>
}

Solution.Web2/Views/Formation/Edit.cshtml
@model Solution.Web2.Models.FormationVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Formation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>FormationVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FormationID)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.IsFullDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsFullDay)
                @Html.ValidationMessageFor(model => model.IsFullDay, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.NbrMax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NbrMax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NbrMax, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Affiche, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Affiche", null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Affiche, "", new { @class = "text-danger" })
        </div>
    </div>

   

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{}

Solution.Web2/Views/Formation/Index.cshtml
@model IPagedList<Solution.Web2.Models.FormationVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;
<button type="button" class="btn btn-default"><a href="@Url.Action("Create", "Formation")">Add Formation</a></button>



<section class="page-header section-notch">
    <div class="overlay">
        <div class="container">
            <h3>Don’t Miss Our Events</h3>
            <ul>
                <li><a href="@Url.Action("Calendar", "Formation")">Voir dans le Calendrier</a></li>
                <li>-</li>
                <li>Events</li>
            </ul>
        </div><!-- container -->
    </div><!-- overlay -->
</section>
<div class="col-lg-4">
    <div class="sidebar">
        <div class="sidebar-item">
            <form>
                @using (Html.BeginForm())
                {
                    //@Html.TextBox("searchString", "", new { @class = "sidebar sidebar-item form" })
                    <input type="text" name="searchString" placeholder="Search Your Course...">
                    <button type="submit" id="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                }
            </form>
        </div>
    </div>
</div>
<!-- Blog -->
<!-- Blog List View -->
<section class="event event-two padding-120">
    <div class="container">
        <div class="event-items">
            <div class="row">
                @if (Model != null)
                {

                    foreach (var item in Model.Reverse())
                    {
                        @Html.Partial("_DisplayFormation", item)
                    }
                }
            </div>
        </div>
    </div>
</section>



@Html.PagedListPager(Model, i => Url.Action("Index", "Formation", new { i, search = Request.QueryString["searchString"] }))

Solution.Web2/Views/Formation/Paricipate.cshtml
@model IEnumerable<Solution.Web2.Models.EnfantVM>

@{
    ViewBag.Title = "Paricipate";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Paricipate</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prenom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.EnfantId }) |
        @Html.ActionLink("Details", "Details", new { id = item.EnfantId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.EnfantId })*@
                    @Html.ActionLink(" Join !", "Paricipate1", new { IdFormation = item.IdFormation , IdEnfant= item.EnfantId}, new { @class = "icon flaticon-symbols" })
                </td>
            </tr>
        }
    }

</table>
@section scripts{}