Solution.Web2/Controllers/EnfantController.cs
using Microsoft.AspNet.Identity;
using Solution.Domain.Entities;
using Solution.Service;
using Solution.Web2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Solution.Web2.Controllers
{
    public class EnfantController : Controller
    {
        public IUserService MyUser;
        public FormationService MyFormationService;
        public ParticipationService MyParticipationService;
        public EnfantService MyEnfantService;
        // GET: Enfant

        public EnfantController()
        {
            MyUser = new UserService();
            MyFormationService = new FormationService();
            MyEnfantService = new EnfantService();
            MyParticipationService = new ParticipationService();
        }


        public ActionResult Index()
        {
            var Enfats = new List<EnfantVM>();
            IEnumerable<Enfant> pm = MyEnfantService.SearchEnfantByParent(User.Identity.GetUserId<int>());
            foreach (Enfant E in pm)
            {
                Enfats.Add(new EnfantVM()
                {
                    EnfantId = E.EnfantId,
                    Age = E.Age,
                    Image = E.Image,
                    Nom = E.Nom,
                    Prenom = E.Prenom,
                    Sexe = E.Sexe
                }
                );
            }
            return View(Enfats);
        }

        // GET: Enfant/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Enfant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Enfant/Create
        [HttpPost]
        public ActionResult Create(EnfantVM enfantVM, HttpPostedFileBase Image, FormCollection collection)
        {
            try
            {
                //if (!ModelState.IsValid || Image == null || Image.ContentLength == 0)
                //{
                //    RedirectToAction("Create");
                //}

                Enfant EnfantDomain = new Enfant()
                {
                    Nom = enfantVM.Nom,
                    Prenom = enfantVM.Prenom,
                    Image = Image.FileName,
                    Age = enfantVM.Age,
                    Sexe = enfantVM.Sexe,
                    //    nomuser = User.Identity.GetUserName(),
                    ParentId = User.Identity.GetUserId<int>()
            };

                MyEnfantService.Add(EnfantDomain);
                MyEnfantService.Commit();

                var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Image.FileName);
                Image.SaveAs(path);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(enfantVM);
            }
        }

        // GET: Enfant/Edit/5
        public ActionResult Edit(int id)
        {
            Enfant p = MyEnfantService.GetById((int)id);
            EnfantVM pm = new EnfantVM()
            {
                Nom = p.Nom,
                Prenom = p.Prenom,
                Age = p.Age,
                Image = p.Image,
                Sexe = p.Sexe
            };
            return View(pm);
        }

        // POST: Enfant/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EnfantVM pm, HttpPostedFileBase Image)
        {
            try
            {
                Enfant p = MyEnfantService.GetById((int)id);
                p.Nom = pm.Nom;
                p.Prenom = pm.Prenom;
                p.Age = pm.Age;
                p.Sexe = pm.Sexe;
                p.Image = Image.FileName;
                p.ParentId = User.Identity.GetUserId<int>();

                MyEnfantService.Update(p);
                MyEnfantService.Commit();

                var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Image.FileName);
                Image.SaveAs(path);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(pm);
            }
        }

        // GET: Enfant/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Enfant/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Enfant p = MyEnfantService.GetById(id);
            MyEnfantService.Delete(p);
            MyEnfantService.Commit();
            // TODO: Add delete logic here
            return RedirectToAction("Index");
        }

        public ActionResult Participation(int id)
        {
            var parts = new List<ParticipationVM>();
            IEnumerable<Participation> pp = MyParticipationService.getByEnfantID(id);
            foreach (Participation p in pp)
            {
                parts.Add(new ParticipationVM()
                {
                    EnfantId = p.EnfantId,
                    FormationID = p.FormationID,
                    Title = p.Title
                });
            }

            return View(parts);
        }

        public ActionResult Annuler(int IdEnfant, int IdFormation)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Annuler(int IdEnfant,int IdFormation, FormCollection collection)
        {
            Participation p = MyParticipationService.Get(x=>x.EnfantId==IdEnfant && x.FormationID==IdFormation);
            MyParticipationService.Delete(p);
            MyParticipationService.Commit();
            // TODO: Add delete logic here

            return RedirectToAction("Index");
        }

    }
}

Solution.Web2/Views/Enfant/Annuler.cshtml
@model Solution.Web2.Models.ParticipationVM

@{
    ViewBag.Title = "Annuler";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Annuler</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParticipationVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Solution.Web2/Views/Enfant/Create.cshtml
@model Solution.Web2.Models.EnfantVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Enfant", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Enfant</h4>
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Image", null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          Boy:   @Html.RadioButtonFor(m => m.Sexe, "male")
          Girl:  @Html.RadioButtonFor(m => m.Sexe, "female")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Solution.Web2/Views/Enfant/Delete.cshtml
@model Solution.Web2.Models.EnfantVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Supprimer</h2>

<h3>Etes-vous sur de vouloir supprimer cet enfant?</h3>
<div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Supprimer" class="btn btn-default" /> |
        <button type="button"  class="btn btn-default"><a href="@Url.Action("Index", "Enfant")">Retour</a></button>

    </div>
    }
</div>

Solution.Web2/Views/Enfant/Edit.cshtml
@model Solution.Web2.Models.EnfantVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Enfant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>EnfantVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EnfantId)

    <div class="form-group">
        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Image", null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            Boy:   @Html.RadioButtonFor(m => m.Sexe, "male")
            Girl:  @Html.RadioButtonFor(m => m.Sexe, "female")
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Solution.Web2/Views/Enfant/Index.cshtml
@model IEnumerable<Solution.Web2.Models.EnfantVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="content-wrapper">
    <button type="button" class="btn btn-default"><a href="@Url.Action("Create", "Enfant")">Ajouter Enfant</a></button>

    <main class="main-content">

        <section class="gallery padding-120">
            <div class="container">
                <div class="gallery-items">
                    @if (Model != null)
                    {

                        foreach (var item in Model)
                        {

                            @Html.Partial("_DisplayEnfant", item)
                        }
                    }
                </div>
            </div>
        </section>
    </main>
</div>



@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdFormation)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdFormation)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.EnfantId }) |
                @Html.ActionLink("Details", "Details", new { id=item.EnfantId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.EnfantId })
            </td>
        </tr>
    }

    </table>*@

Solution.Web2/Views/Enfant/Participation.cshtml
@model IEnumerable<Solution.Web2.Models.ParticipationVM>

@{
    ViewBag.Title = "Participation";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Les Participations</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
            @Html.ActionLink("Annuler", "Annuler", new {  IdEnfant=item.EnfantId , IdFormation=item.FormationID })
        </td>
    </tr>
}

</table>

Solution.Web2/Views/Enfant/_DisplayEnfant.cshtml
@model Solution.Web2.Models.EnfantVM
@{string path = "~/Content/Uploads/" + @Model.Image;}


<div class="gallery-item branding packing">
    <div class="gallery-image">
        <img src="@Url.Content(path)" alt="gallery image" class="img-responsive">
        <div class="gallery-overlay" style="color: #ffc000"><div class="bg" style="color: #ffc000"></div></div>
        <div class="gallery-content">
           <h6>@Html.ActionLink("Modifier", "Edit", new { id = Model.EnfantId }, new { @style = "color:white" })</h6>
            <h6>@Html.ActionLink("Supprimer", "Delete", new { id = Model.EnfantId }, new { @style = "color:white" })</h6>
            <h6>@Html.ActionLink("Participations", "Participation", new { id = Model.EnfantId }, new { @style = "color:white" })</h6>
            <h4>@Model.Nom @Model.Prenom</h4>
            <span>Age: @Model.Age</span>
            
        </div>
    </div>
</div>