Solution.Web2/Controllers/PublicationController.cs
using PagedList;
using Solution.Domain.Entities;
using Solution.Service;
using Solution.Web2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Solution.Web2.Controllers
{
    public class PublicationController : Controller


    {

        ICommentService comserv = new CommentService();
        IUserService userserv = new UserService();
        IPublicationService pubserv = new PublicationService();
        IReplyService repserv = new ReplyService();
        ILikeService likeserv = new LikeService();

        // GET: Publication

        // GET: Formation
        public ActionResult Index(string searchString, int? i)
        {
            var Publications = new List<PublicationVM>();
            foreach (Publication p in pubserv.SearchFormByName(searchString))
            {

                Publications.Add(new PublicationVM()
                {
                    title = p.title,
                    description = p.description,
                    creationDate = p.creationDate,
                    image = p.image,
                    nomuser = p.nomuser,
                    ownerimg = p.ownerimg,
                    OwnerId = p.OwnerId,
                    PublicationId = p.PublicationId,
                    visibility = (VisibilityVM)p.visibility
                });

            }
            return View(Publications.ToPagedList(i ?? 1, 3));

        }


        // GET: Publication/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publication p;
            p = pubserv.GetById((int)id);
            if (p == null) { return HttpNotFound(); }
            PublicationVM pvm = new PublicationVM()
            {
                creationDate = p.creationDate,
                description = p.description,
                image = p.image,
                //OwnerId=p.OwnerId,
                PublicationId = p.PublicationId,
                title = p.title,
                visibility = (VisibilityVM)p.visibility
            };
            GetComments((int)id);
            return View(pvm);
        }

        // GET: Publication/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Publication/Create
        [HttpPost]
        public ActionResult Create(PublicationVM PublicationVM, HttpPostedFileBase Image)
        {
            Publication PublicationDomain = new Publication();


            PublicationDomain.title = PublicationVM.title;
            PublicationDomain.creationDate = DateTime.UtcNow;
            PublicationDomain.description = PublicationVM.description;
            PublicationDomain.visibility = (Visibility)PublicationVM.visibility;
            PublicationDomain.image = Image.FileName;
            PublicationDomain.nomuser = "stella"; //User.Identity.GetUserName();
            PublicationDomain.OwnerId = "f43c21cf-f35a-4897-a9e3-343c00afe7b4";//User.Identity.GetUserId();
            PublicationDomain.ownerimg = "exp.png"; // MyUser.GetById(User.Identity.GetUserId()).image;



            pubserv.Add(PublicationDomain);
            //notifserv.Add(comp2);
            pubserv.Commit();


            var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Image.FileName);
            Image.SaveAs(path);
            return RedirectToAction("Index");
        }

        // GET: Publication/Edit/5
        public ActionResult Edit(int id)
        {
            Publication p = pubserv.GetById((int)id);
            PublicationVM pm = new PublicationVM()
            {
                creationDate = p.creationDate,
                description = p.description,
                image = p.image,
                OwnerId = p.OwnerId,
                PublicationId = p.PublicationId
            ,
                title = p.title,
                visibility = (VisibilityVM)p.visibility
            };
            return View(pm);
        }

        // POST: Publication/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PublicationVM pm, HttpPostedFileBase Image)
        {
            try
            {

                Publication p = pubserv.GetById((int)id);
                p.description = pm.description;
                p.title = pm.title;
                p.visibility = (Visibility)pm.visibility;
                p.image = Image.FileName;

                pubserv.Update(p);
                pubserv.Commit();

                var path = Path.Combine(Server.MapPath("~/Content/Uploads"), Image.FileName);
                Image.SaveAs(path);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(pm);
            }
        }

        // GET: Publication/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Publication/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Publication p = pubserv.GetById(id);
            pubserv.Delete(p);
            pubserv.Commit();
            // TODO: Add delete logic here

            return RedirectToAction("Create");
        }

        [HttpPost]
        public ActionResult CreateComment(string con, int id)
        {


            Comment comment = new Comment()
            {
                Contenu = con,
                PublicationId = id

            };

            comserv.Add(comment);
            comserv.Commit();



            return Json(comment, JsonRequestBehavior.AllowGet);

        }

        public PartialViewResult GetComments(int idpub)
        {
            var Comments = new List<CommentVM>();
            foreach (Comment p in comserv.GetMany())
            {
                if (p.PublicationId == idpub)
                {
                    Comments.Add(new CommentVM()
                    {
                        nomuser = p.nomuser,
                        ownerimg = p.ownerimg,
                        OwnerId = p.OwnerId,
                        PublicationId = p.PublicationId,
                        CommentId = p.CommentId,
                        Contenu = p.Contenu
                    });
                }


            }

            return PartialView("Comments", Comments);
        }

        [HttpPost]
        public PartialViewResult PostComment(string contenu, int idpub)
        {



            Comment comment = new Comment()
            {
                Contenu = contenu,
                PublicationId = idpub,
                nomuser = "stella",
                OwnerId = "f43c21cf-f35a-4897-a9e3-343c00afe7b4",
                ownerimg = "img"

            };

            comserv.Add(comment);
            comserv.Commit();

            //var Comments = new List<CommentVM>();
            //foreach (Comment p in MyCommentService.GetMany().ToList())
            //{
            //    if (p.PublicationId == idpub)
            //    {
            //        Comments.Add(new CommentVM()
            //        {
            //            CommentId = p.CommentId,
            //            Contenu = p.Contenu
            //        });
            //    }


            //}

            return PartialView("SingleComment", new CommentVM
            {
                CommentId = comment.CommentId,
                PublicationId = comment.PublicationId,
                Contenu = comment.Contenu
            });

        }

        [HttpPost]
        public PartialViewResult DeleteComment(int id, int idpub, FormCollection collection)
        {


            Comment comment = comserv.GetById(id);


            comserv.Delete(comment);
            comserv.Commit();

            var Comments = new List<CommentVM>();
            foreach (Comment p in comserv.GetMany())
            {
                if (p.PublicationId == idpub)
                {
                    Comments.Add(new CommentVM()
                    {
                        PublicationId = idpub,
                        CommentId = p.CommentId,
                        Contenu = p.Contenu
                    });
                }


            }
            Console.WriteLine(id + "     " + idpub);
            return PartialView("Comments", Comments);

        }

        public PartialViewResult GetLikes(int idpub)
        {
            LikeVM like;
            Like test = null;
            foreach (Like l in likeserv.GetMany())
            {

                if ((l.idPub == idpub) && (l.idUser.Equals("f43c21cf-f35a-4897-a9e3-343c00afe7b4")))
                {
                    test = l;
                }


            }

            if (test == null)
            {
                return PartialView("AddLike", new LikeVM { idPub = idpub });
            }
            else
            {
                return PartialView("DellLike", new LikeVM { idPub = idpub });
            }


        }


        [HttpPost]
        public PartialViewResult DeleteLike(int idp, FormCollection collection)
        {


            Like test = null;
            foreach (Like l in likeserv.GetMany())
            {
                if ((l.idPub == idp) && (l.idUser == "f43c21cf-f35a-4897-a9e3-343c00afe7b4"))
                {
                    test = l;
                }


            }


            likeserv.Delete(test);
            likeserv.Commit();


            return PartialView("AddLike", new LikeVM { idPub = idp });

        }

        [HttpPost]
        public PartialViewResult AddLike(int idpa)
        {


            Like like = new Like()
            {
                idPub = idpa,
                idUser = "f43c21cf-f35a-4897-a9e3-343c00afe7b4"

            };

            likeserv.Add(like);
            likeserv.Commit();

Solution.Web2/Views/Publication/AddOrEdit.cshtml
@model Solution.Web2.Models.CommentVM







@using (Html.BeginForm("AddOrEdit", "Publication", FormMethod.Post, new { onSubmit = "return jQueryAjaxPost(this);" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group" style="margin: 0;">



        @Html.LabelFor(model => model.Contenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenu, new { htmlAttributes = new { @class = "form-control style-d" } })
            @Html.ValidationMessageFor(model => model.Contenu, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>



    </div>


}

Solution.Web2/Views/Publication/Create.cshtml
@model Solution.Web2.Models.PublicationVM




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>
    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href=@Url.Content("/global_assets/css/icons/icomoon/styles.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/bootstrap.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/bootstrap_limitless.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/layout.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/components.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/colors.min.css") rel="stylesheet" type="text/css">
    <script src=@Url.Content("/global_assets/js/demo_pages/animations_css3.js")></script>
    <link href=@Url.Content("/global_assets/css/extras/animate.min.css") rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
    <link href=@Url.Content("/global_assets/css/icons/icomoon/styles.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/bootstrap.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/bootstrap_limitless.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/layout.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/components.min.css") rel="stylesheet" type="text/css">
    <link href=@Url.Content("/assets/css/colors.min.css") rel="stylesheet" type="text/css">

    <!-- Core JS files -->
    <script src=@Url.Content("/global_assets/js/main/jquery.min.js")></script>
    <script src=@Url.Content("/global_assets/js/main/bootstrap.bundle.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/loaders/blockui.min.js")></script>
    <!-- /core JS files -->
    <!-- Theme JS files -->
    <!-- Theme JS files -->
    <script src=@Url.Content("global_assets/js/plugins/notifications/jgrowl.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/notifications/noty.min.js")></script>
    <link rel="stylesheet" href="http://www.jacklmoore.com/colorbox/example1/colorbox.css" />

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://www.jacklmoore.com/colorbox/jquery.colorbox.js"></script>
    <script src=@Url.Content("/assets/js/app.js")></script>
    <script src=@Url.Content("/global_assets/js/demo_pages/extra_jgrowl_noty.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/visualization/d3/d3.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/visualization/d3/d3_tooltip.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/styling/switchery.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/ui/moment/moment.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/pickers/daterangepicker.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/styling/switchery.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/styling/uniform.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/selects/select2.min.js")></script>


    <script src=@Url.Content("/assets/js/app.js")></script>
    <script src=@Url.Content("/global_assets/js/demo_pages/dashboard.js")></script>
    <script src=@Url.Content("/global_assets/js/demo_pages/form_actions.js")></script>
    <script src=@Url.Content("/global_assets/js/demo_pages/editor_summernote.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/editors/summernote/summernote.min.js")></script>
    <script src=@Url.Content("/global_assets/js/plugins/forms/styling/uniform.min.js")></script>
    <script src=@Url.Content("/global_assets/js/demo_pages/form_layouts.js")></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <script src=@Url.Content("/global_assets/js/demo_pages/form_inputs.js")></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://www.jacklmoore.com/colorbox/jquery.colorbox.js"></script>
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <style>
        .bounce {
            -webkit-animation-name: bounce;
            animation-name: bounce;
            -webkit-transform-origin: center bottom;
            transform-origin: center bottom;
        }
    </style>




</head>
<body>




    <div class="card">
        <div class="card-header header-elements-inline">
            <h3 class="card-title">Create Publication </h3>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Publication", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group row">
                    <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Title :</b></label>
                    <div class="col-lg-9">
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Your description :</b></label>
                    <div class="col-lg-9">
                        @Html.TextAreaFor(model => model.description, new { @class = "form-control", rows = "5", cols = "3", placeholder = "You can descripe the publication here...", })
                        @Html.ValidationMessageFor(model => model.description)
                    </div>
                </div>

                <div class="form-group">

                    <div class="form-group">


                        <div class="form-input-styled">
                            @Html.TextBox("Image", null, new
                       {
                           type = "file",
                          @class = "form-input-styled"
                       })
                            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                            <span class="form-text text-muted">Accepted formats: gif, png, jpg. Max file size 2Mb</span>
                        </div>
                    </div>

                </div>
                <div class="form-group row">
                    <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Visibility :</b></label>
                    <div class="form-control-select2-icons">
                        @Html.EnumDropDownListFor(model => model.visibility, "Please select Visibility")
                        @Html.ValidationMessageFor(model => model.visibility, "", new { @class = "text-danger" })

                    </div>

                </div>




                <div class="text-right">


                    <button type="submit" id="toastr" onclick="create()" class="btn btn-primary animated  fadeIn infinite delay-4s">Submit <i class="icon-paperplane ml-2"></i></button>


                    <script type="text/javascript">

                        function create() {
                            toastr.success("Your Pub was send succefully !");
                        }
                    </script>

                </div>
                <div class="text-left">
                    <button class="btn" style="background-color:transparent">@Html.ActionLink("Back to List", "Index")<i class="icon-home ml-2"></i></button>
                </div>




            }





</body>
</html>

Solution.Web2/Views/Publication/Create2.cshtml
@model Solution.Web2.Models.PublicationVM

@using (Html.BeginForm("Create2", "Publication", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create new publication</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group row">
            <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Title :</b></label>
            <div class="col-lg-9">
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Your description :</b></label>
            <div class="col-lg-9">
                @Html.TextAreaFor(model => model.description, new { @class = "form-control", rows = "5", cols = "3", placeholder = "You can descripe the publication here...", })
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">

            <div class="form-group">


                <div class="form-input-styled">
                    @Html.TextBox("Image", null, new
                   {
                       type = "file",
                       @class = "form-input-styled"
                   })
                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                    <span class="form-text text-muted">Accepted formats: gif, png, jpg. Max file size 2Mb</span>
                </div>
            </div>

        </div>
          <div class="form-group row">
                    <label class="col-lg-3 col-form-label"><b class="animated  zoomInUp delay-1s">Visibility :</b></label>
                    <div class="form-control-select2-icons">
                        @Html.EnumDropDownListFor(model => model.visibility, "Please select Visibility")
                        @Html.ValidationMessageFor(model => model.visibility, "", new { @class = "text-danger" })
                     
                    </div>
                
                </div>




        <div class="text-right">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="toastr" onclick="create()" class="btn btn-primary animated  fadeIn infinite delay-1s">Submit <i class="icon-paperplane ml-2"></i></button>


                <script type="text/javascript">

                    function create() {
                        toastr.success("Your Pub was send succefully !");
                    }
                </script>
            </div>
        </div>

        </div>
}

<div class="text-left">
    <button class="btn" style="background-color:transparent">@Html.ActionLink("Back to List", "Index")<i class="icon-home ml-2"></i></button>
</div>

Solution.Web2/Views/Publication/Details.cshtml
@model Solution.Web2.Models.PublicationVM
@{string path = "~/Content/Uploads/" + @Model.image;}




<hr style="border:none" />

<main class="main-content">

    <!-- Blog -->

    <div class="container">
        <div class="row">
            <!-- Blog Content -->
            <div class="col-lg-9 col-md-9 col-sm-7 col-xs-12">

                <!-- Blog detail -->
                <div class="blog-detail-holder" style="border:6px solid #999999;border-radius: 30px">
                    <div class="author-header" style="background-color:white; ;border-radius: 30px 30px 0px 0px ;" ">
                        <h2 style="text-align:center">@Model.title</h2>
                        <div class="aurhor-img-name pull-left">
                            <img src="@Url.Content("~/Content/Uploads/stella.jpg")" alt="" height="60" width="60">
                            <strong>by <i class="red-color">Stella</i></strong>
                            <span>on @Model.creationDate </span>
                        </div>
                        <div class="share-option pull-right">
                            <span id="share-btn1"><i class="fa fa-share-alt"></i>Share</span>
                            <div id="show-social-icon1" class="on-hover-share">
                                <ul class="social-icons">
                                    <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a class="youtube" href="#"><i class="fa fa-youtube-play"></i></a></li>
                                    <li><a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="blog-detail">
                        <figure>
                            <img src="@Url.Content(path)" width="1000px" height="800" " alt="">
                        </figure>
                        <article>
                            <p>@Model.description</p>
                        </article>
                    </div>
                    <div class="tags-holder">
                        <ul class="tags-list pull-left">
                            <li><i class="fa fa-tags"></i>Tags</li>
                         
                           
                            <li><a  id="shCom">Comments</a></li>
                        </ul>
                        <ul class="social-icons pull-right">
                            <li>Share this post</li>
                            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a class="youtube" href="#"><i class="fa fa-youtube-play"></i></a></li>
                            <li><a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a></li>
                        </ul>
                    </div>
               
                    <div id="Divcomment" style="display:none">
                        @Html.Action("GetComments", new { idpub = Model.PublicationId })
                    </div>
                    <div class="form-group" style="margin: 0;">
                        <textarea id="comm" class="form-control style-d" rows="2" placeholder="Write Comments here..."></textarea>
                        <i class="fa fa-pencil-square-o"></i>
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.PublicationId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = Model.PublicationId }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>

        </div>
</main>

@section Scripts{
    <script>
    $(function() {
        function getContent(){
            return document.getElementById("comm").value
        }

        $("#comm").keyup(function (e){
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if(keycode == '13'){
                var idpub=@Model.PublicationId;
                var contenu = document.getElementById("comm").value;
                if (contenu == "") {
                    window.alert("un commentairene peut pas etre vide ");
                }
                else {

                    $.ajax({
                        url: '@Url.Action("PostComment", "Publication")' + "?contenu=" + contenu + "&idpub=" + idpub,
                        type: "POST",
                        success: function (result) {
                            $('#Divcomment').append(result)
                            $("#comm").val("")
                        }
                        //data: {id: idpub, con: contenu},
                    })
                    /* .done(function (response) {
                     debugger;

                     //$('#Divcomment').html(response);
                     alert(respose.d)

                 });*/
                }
            }


        })
    });
        $("#shCom").click(function(){
            $("#Divcomment").toggle();
        });
      
    </script>
}

Solution.Web2/Views/Publication/SingleComment.cshtml
@model Solution.Web2.Models.CommentVM
@{

   
}
<ul>
    <li style="padding: 15px;background: #9c9c9c47;">
        <img class="position-center-x" src="@Url.Content("~/Content/Uploads/stella.jpg")" style="width:80px;
height:80px;">

        <div class="comment-detail">
            <h5><a href="#">by Stella</a></h5>
            <span>09/06/2020 </span>
            <p>@Model.Contenu</p>
        </div>
    </li>
</ul>

<div style="background: #9c9c9c47 ; height: 42px; ">
    <div class="share-option pull-right">
        <span><a href="javascript:void(0)" onclick="supprimerCommentaire()" style="float: right"><i class="fa fa-trash-o fa-lg"></i></a></span>
    </div>
</div>
<input type="hidden" id="pub" value="@Model.PublicationId" />
<input type="hidden" id="co" value="@Model.CommentId" />

Solution.Web2/Views/Publication/SingleReply.cshtml
@model Solution.Web2.Models.ReplyVM

@{
    ViewBag.Title = "SingleReply";
    
}


<ul>


    <li class="sub-comment">
        <ul>
            <li>
                <img class="position-center-x" src="@Url.Content("~/Content/Uploads/stella.jpg")" style="width:60px;
height:60px;">
                <div class="comment-detail">
                    <h5><a href="#">Stella</a></h5>
                    <span>Juin 06, 2020</span>
                    <p>@Model.Contenu</p>

                </div>
            </li>
        </ul>
        </li></ul>